#!/bin/bash

# github

repo_create_keys() {
	
	ssh-keygen -t rsa -C $GITHUB_ACCOUNT_EMAIL
	ssh-add ~/.ssh/id_rsa
}

repo_backup_keys() {

}

repo_restore_keys() {
	
}

repo_create() {
	
}

repo_commit() {
	
}

# virtual servers

gitbox_sync_upload() {

	local DIRECTION="download"
	
	local LOCAL_PATH=$HOME"/projects/"$PROJECT_NAME
	local LOCAL_FILE=""
	
	local PROJECT_NAME=$1

	local REMOTE_PATH=$2
	local REMOTE_FILE="*"
	local REMOTE_USER="ubuntu"
	local REMOTE_ADDRESS="192.168.1.117"

	ssh_ssh $LOCAL_PATH$PROJECT_NAME/$LOCAL_FILE $REMOTE_USER@$REMOTE_ADDRESS:$REMOTE_PATH$PROJECT_NAME/$REMOTE_FILE
}

gitbox_sync_download() {

	local DIRECTION="download"
	
	local LOCAL_PATH=$HOME"/projects/"$PROJECT_NAME
	local LOCAL_FILE="*"
	
	local PROJECT_NAME=$1

	local REMOTE_PATH=$2
	local REMOTE_FILE=""
	local REMOTE_USER="ubuntu"
	local REMOTE_ADDRESS="192.168.1.117"

	ssh_ssh $REMOTE_USER@$REMOTE_ADDRESS:$REMOTE_PATH$PROJECT_NAME/$REMOTE_FILE $LOCAL_PATH$PROJECT_NAME/$LOCAL_FILE
}

gitbox_sync_download_deck() {

	local PROJECT_NAME="deck"
	local REMOTE_PATH="/domains/"$PROJECT_NAME"/html/"

	gitbox_sync_download $PROJECT_NAME $REMOTE_PATH
}

gitbox_sync_upload_deck() {

	local PROJECT_NAME="deck"
	local REMOTE_PATH="/domains/"$PROJECT_NAME"/html/"

	gitbox_sync_upload $PROJECT_NAME $REMOTE_PATH
}



lampbox_sync_upload() {

	local DIRECTION="download"
	
	local LOCAL_PATH=$HOME"/projects/"$PROJECT_NAME
	local LOCAL_FILE=""
	
	local PROJECT_NAME=$1

	local REMOTE_PATH=$2
	local REMOTE_FILE="*"
	local REMOTE_USER="ubuntu"
	local REMOTE_ADDRESS="192.168.1.117"

	ssh_ssh $LOCAL_PATH$PROJECT_NAME/$LOCAL_FILE $REMOTE_USER@$REMOTE_ADDRESS:$REMOTE_PATH$PROJECT_NAME/$REMOTE_FILE
}

lampbox_sync_download() {

	local DIRECTION="download"
	
	local LOCAL_PATH=$HOME"/projects/"$PROJECT_NAME
	local LOCAL_FILE="*"
	
	local PROJECT_NAME=$1

	local REMOTE_PATH=$2
	local REMOTE_FILE=""
	local REMOTE_USER="ubuntu"
	local REMOTE_ADDRESS="192.168.1.117"

	ssh_ssh $REMOTE_USER@$REMOTE_ADDRESS:$REMOTE_PATH$PROJECT_NAME/$REMOTE_FILE $LOCAL_PATH$PROJECT_NAME/$LOCAL_FILE
}

lampbox_sync_download_ideiasinsolitas() {

	local PROJECT_NAME="ideiasinsolitas"
	local REMOTE_PATH="/domains/"$PROJECT_NAME"/html/"

	lampbox_sync_download $PROJECT_NAME $REMOTE_PATH
}

lampbox_sync_upload_ideiasinsolitas() {

	local PROJECT_NAME="ideiasinsolitas"
	local REMOTE_PATH="/domains/"$PROJECT_NAME"/html/"

	lampbox_sync_upload $PROJECT_NAME $REMOTE_PATH
}

lampbox_sync_download_radar() {

	local PROJECT_NAME="radar"
	local REMOTE_PATH="/domains/"$PROJECT_NAME"/html/"

	lampbox_sync_download $PROJECT_NAME $REMOTE_PATH
}

lampbox_sync_upload_radar() {

	local PROJECT_NAME="radar"
	local REMOTE_PATH="/domains/"$PROJECT_NAME"/html/"

	lampbox_sync_upload $PROJECT_NAME $REMOTE_PATH
}

lampbox_sync_download_wordpress() {

	local PROJECT_NAME="wordpress"
	local REMOTE_PATH="/domains/"$PROJECT_NAME"/html/"

	lampbox_sync_download $PROJECT_NAME $REMOTE_PATH
}

lampbox_sync_upload_wordpress() {

	local PROJECT_NAME="wordpress"
	local REMOTE_PATH="/domains/"$PROJECT_NAME"/html/"

	lampbox_sync_upload $PROJECT_NAME $REMOTE_PATH
}


ii_sync_upload() {

	local DIRECTION="download"
	
	local LOCAL_PATH=$HOME"/projects/"$PROJECT_NAME
	local LOCAL_FILE=""
	
	local PROJECT_NAME=$1

	local REMOTE_PATH=$2
	local REMOTE_FILE="*"
	local REMOTE_USER="pedrokoblitz.com.br"
	local REMOTE_ADDRESS="s169616.gridserver.com"

	ssh_ssh $LOCAL_PATH$PROJECT_NAME/$LOCAL_FILE $REMOTE_USER@$REMOTE_ADDRESS:$REMOTE_PATH$PROJECT_NAME/$REMOTE_FILE
}

ii_sync_download() {

	local DIRECTION="download"
	
	local LOCAL_PATH=$HOME"/projects/"$PROJECT_NAME
	local LOCAL_FILE="*"
	
	local PROJECT_NAME=$1

	local REMOTE_PATH=$2
	local REMOTE_FILE=""
	local REMOTE_USER="pedrokoblitz.com.br"
	local REMOTE_ADDRESS="s169616.gridserver.com"

	ssh_ssh $REMOTE_USER@$REMOTE_ADDRESS:$REMOTE_PATH$PROJECT_NAME/$REMOTE_FILE $LOCAL_PATH$PROJECT_NAME/$LOCAL_FILE
}

ii_sync_download_ideiasinsolitas() {

	local PROJECT_NAME="ideiasinsolitas"
	local REMOTE_PATH="/domains/"$PROJECT_NAME"/html/"

	ii_sync_download $PROJECT_NAME $REMOTE_PATH
}

ii_sync_upload_ideiasinsolitas() {

	local PROJECT_NAME="ideiasinsolitas"
	local REMOTE_PATH="/domains/"$PROJECT_NAME"/html/"

	ii_sync_upload $PROJECT_NAME $REMOTE_PATH
}

ii_sync_download_radar() {

	local PROJECT_NAME="radar"
	local REMOTE_PATH="/domains/"$PROJECT_NAME"/html/"

	ii_sync_download $PROJECT_NAME $REMOTE_PATH
}

ii_sync_upload_radar() {

	local PROJECT_NAME="radar"
	local REMOTE_PATH="/domains/"$PROJECT_NAME"/html/"

	ii_sync_upload $PROJECT_NAME $REMOTE_PATH
}

ii_sync_download_wordpress() {

	local PROJECT_NAME="wordpress"
	local REMOTE_PATH="/domains/"$PROJECT_NAME"/html/"

	ii_sync_download $PROJECT_NAME $REMOTE_PATH
}

ii_sync_upload_wordpress() {

	local PROJECT_NAME="wordpress"
	local REMOTE_PATH="/domains/"$PROJECT_NAME"/html/"

	ii_sync_upload $PROJECT_NAME $REMOTE_PATH
}




# appfunc
# 3R Studio

3R_ec2_main_sync() {

	local KEY=$3R_KEY
	local SECRET=$3R_SECRET
	local PATH=$1
	local S3NAME=$2

	ec2_main_sync $KEY $SECRET $PATH $S3NAME
}

3R_s3_main_sync() {

	local PATH=$1
	local S3NAME=$2

	# boto-rsync -aAKIAJSPFIMI6TEUUHLRA -sjK1TlLcfC4lYiNo6SBCWc5YQYs6wjm9UTKER3AAF -n /home/dev/aws/sites/casamento/ s3://casamento-mundoinesquecivel/

	s3_main_sync $KEY $SECRET $PATH $S3NAME
}

3R_rds_backup() {
	
	local $DB_NAME=$1 
	local $FILE=$2

	rds_backup $DB_USER $DB_PASSWORD $DB_HOST $DB_NAME $FILE
}

3R_rds_restore() {
	
	local $DB_NAME=$1 
	local $FILE=$2

	rds_restore $DB_USER $DB_PASSWORD $DB_HOST $DB_NAME $FILE
}


main() {

	local CMD=$1
	local ACCOUNT=$2

	case "$CMD" in
	    rds_restore)
			`$ACCOUNT_rds_restore`
			;;
	    rds_backup)
			`$ACCOUNT_rds_backup`
			;;
		ec2_main_sync)
			`$ACCOUNT_ec2_main_sync`
			;;
		s3_main_sync)
			`$ACCOUNT_s3_main_sync`
			;;
	esac
}

main